baseURL = "https://www.openlifter.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "OpenLifter"
theme = "rusty"

[params]
  releaseVersion = "1.0.1"

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params]
      placeholder = "Placeholder"

  [languages.eo]
    languageName = "Esperanto"
    weight = 20
    [languages.eo.params]
      placeholder = "Placeholder"

  [languages.zh-Hans]
    languageName = "简体中文"
    weight = 20
    [languages.zh-Hans.params]
      placeholder = "Placeholder"
